int_putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int_islower(int c);
int_isalpha(int c);
int print_sign(int n);
int abs(int);int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int,int);
void print_to_97(int n);
